# Base Image
FROM node:16-alpine
# Change workdir to 
WORKDIR /usr/app
# Copy package.json into the container
COPY ./package.json .
# Install dependencies
RUN npm install
# Copy the other files into the container
COPY . .
# Run 
CMD ["npm", "run", "serve"]
